blank_issues_enabled: false
contact_links:
  - name: Community Forum
    url: https://splunkcommunity.slack.com/archives/C04DC8JJ6
    about: For general questions, use the forum instead of opening an issue.